export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_NOT_EXISTS = "USER_NOT_EXISTS";
export const USER_EXISTS = "USER_EXISTS";

export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const USER_SIGNUP_LOADING = "USER_SIGNUP_LOADING";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";

export const LOGIN_TOKEN = "login-token";
